# Generated by Django 3.2.6 on 2021-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210817_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
