# Generated by Django 3.2.6 on 2021-08-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('AS', 'آذربایجان شرقی'), ('AG', 'آذربایجان غربی'), ('AR', 'اردبیل'), ('ES', 'اصفهان'), ('AL', 'البرز'), ('IL', 'ایلام'), ('BU', 'بوشهر'), ('TH', 'تهران'), ('CB', 'چهارمهال و بختیاری'), ('KJ', 'خراسان جنوبی'), ('KR', 'خراسان رضوی'), ('KS', 'خراسان شمالی'), ('KZ', 'خوزستان'), ('ZN', 'زنجان'), ('SM', 'سمنان'), ('SB', 'سیستان و بلوچستان'), ('FR', 'فارس'), ('QZ', 'قزوین'), ('QM', 'قم'), ('KD', 'کردستان'), ('KN', 'کرمان'), ('KM', 'کرمانشاه'), ('KB', 'کهگیلویه و بویراحمد'), ('GL', 'گلستان'), ('GI', 'گیلان'), ('LR', 'لرستان'), ('MZ', 'مازندران'), ('MK', 'مرکزی'), ('HR', 'هرمزگان'), ('HM', 'همدان'), ('YZ', 'یزد')], max_length=120)),
                ('postal_code', models.CharField(max_length=10)),
                ('full_address', models.TextField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PERSONNEL', 'Personnel'), ('ADMIN', 'Admin')], max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, default='avatar.png', null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'ادمین',
                'verbose_name_plural': 'ادمین ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
