# Generated by Django 3.2.6 on 2021-08-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
