# Generated by Django 3.2.6 on 2021-08-26 07:15

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city'),
        ),
    ]
