# Generated by Django 3.2.6 on 2021-08-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
