# Generated by Django 3.2.6 on 2021-08-20 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountPercentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Percent', 'Percent'), ('Amount', 'Amount')], max_length=7)),
                ('percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('amount', models.FloatField(blank=True, null=True)),
                ('max_discount', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تخفیف مقداری/درصدی',
                'verbose_name_plural': 'تخفیف های مقداری/درصدی',
            },
        ),
        migrations.CreateModel(
            name='CodeDiscount',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تخفیف کدی',
                'verbose_name_plural': 'تخفیف های کدی',
            },
        ),
    ]
