# Generated by Django 3.2.6 on 2021-09-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20210820_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='codediscount',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
